sudo: false

language: node_js

notifications:
  email: false

node_js:
  - 8.4.0

cache:
  directories:
  - node_modules

before_install:
  - npm install -g npm@latest

  install:
  - npm install

script: npm run build
